# Use the official Nginx image as a base
FROM nginx

# Copy the custom Nginx configuration file to the container
COPY nginx.conf /etc/nginx/nginx.conf

# Copy the HTML file with "Hello, World!" message to the container
COPY index.html /usr/share/nginx/html/index.html
