apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-vpa
  labels:
    app: nginx-vpa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-vpa
  template:
    metadata:
      labels:
        app: nginx-vpa
    spec:
      containers:
      - name: c-nginx
        image: nginx
        ports:
        - containerPort: 80
        resources:
           requests:
             memory: 20Mi
             cpu: "0.25"
           limits:
             memory: 400Mi
             cpu: "1"
#---

#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service
#spec:
#  selector:
#    app: nginx
#  type: LoadBalancer
#  ports:
#    - port: 80
#      targetPort: 80
#      nodePort: 30001

