apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: my-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: "Deployment"
    name: "deployment-vpa"
  updatePolicy:
    updateMode: "Off"   ## off mode prepared for productions
#  resourcePolicy:
#    containerPolicies:
#      - containerName: "*"
#        minAllowed:
#          cpu: 50m
#          memory: 100Mi
#        maxAllowed:
#          cpu: 1
#          memory: 1Gi
