apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-resource
  labels:
    app: nginx-resource-management
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-resource-management
  template:
    metadata:
      labels:
        app: nginx-resource-management
    spec:
      containers:
      - name: nginx-container
        image: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1.2
            memory: 1.2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-resource
spec:
  selector:
    app: nginx-resource-management
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009

