apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:

      volumes:
        - name: volume1
          hostPath:
            path: /mnt/data


      volumes:
        - name: volume2
          hostPath:
            path: /mnt/data_v2

      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

          volumeMounts:
            - name: volume1
              mountPath: /usr/share/nginx/html


      containers:
        - name: nginx-container2
          image: nginx
          ports:
            - containerPort: 81

          volumeMounts:
            - name: volume2
              mountPath: /usr/share/nginx/html


