apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  namespace: namespace-project
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
