apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeport-deployment
  labels:
    app: nodeport-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeport-nginx
  template:
    metadata:
      labels:
        app: nodeport-nginx
    spec:
      containers:
      - name: nodeport-nginx
        image: nginx
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
spec:
  selector:
    app: nodeport-nginx
  type: NodePort
  ports:
    - port: 8086
      targetPort: 80
      nodePort: 30001

