apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test1-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: "test1-storage-class"
