apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.appName }}
  labels:
    app: {{  .Values.appLabel }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{  .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{  .Values.appLabel }}
    spec:
      containers:
      - name: c-nginx
        image: nginx:latest
        ports:
        - containerPort: 80

#---

#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx-service
#spec:
#  selector:
#    app: nginx
#  type: LoadBalancer
#  ports:
#    - port: 80
#      targetPort: 80
#      nodePort: 30001

