apiVersion: v1
kind: Service
metadata:
  name: {{  .Values.appNameservice }}
spec:
  selector:
    app: {{  .Values.appLabel }}
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30005
 ## type: LoadBalancer
