apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-selector
  labels:
    app: nginx-scheduling-selector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-scheduling-selector
  template:
    metadata:
      labels:
        app: nginx-scheduling-selector
    spec:
      nodeSelector:
       team: team1
      containers:
      - name: c-nginx
        image: raemondarellano/nginx-k8s:latest
        ports:
        - containerPort: 80


# first you need to label the nodes
# example
# kubectl label node name_of_nodes team=myteam
# kubectl label node name_of_nodes2 team=myteam

# to show all labels in nodes
# kubectl get nodes --show-labels

# to show specific labels in nodes
# kubectl get nodes -l team=myteam
