apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deployment
  labels:
    app: lb-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lb-nginx
  template:
    metadata:
      labels:
        app: lb-nginx
    spec:
      containers:
      - name: lb-nginx
        image: c_nginx
        ports:
        - containerPort: 80
