apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-deployment
  labels:
    app: lb-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lb-nginx
  template:
    metadata:
      labels:
        app: lb-nginx
    spec:
      containers:
      - name: lb-nginx
        image: c_nginx
        ports:
        - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app: lb-nginx
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
#      nodePort: 30001

